import { createClient } from '@supabase/supabase-js'

// Environment variables - you'll need to add these to your .env.local file:
// NEXT_PUBLIC_SUPABASE_URL=https://trdpqqyesooexjudrwtp.supabase.co
// NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Please check your .env.local file.')
}

// Client-side Supabase instance
export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Database types (will be auto-generated by Supabase)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          birth_year: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          birth_year?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          birth_year?: number | null
          updated_at?: string
        }
      }
      memories: {
        Row: {
          id: string
          title: string | null
          text_content: string | null
          user_id: string
          timezone_id: string | null
          date_precision: string | null
          approximate_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title?: string | null
          text_content?: string | null
          user_id: string
          timezone_id?: string | null
          date_precision?: string | null
          approximate_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string | null
          text_content?: string | null
          user_id?: string
          timezone_id?: string | null
          date_precision?: string | null
          approximate_date?: string | null
          updated_at?: string
        }
      }
      timezones: {
        Row: {
          id: string
          title: string
          description: string | null
          type: string
          start_date: string | null
          end_date: string | null
          location: string | null
          invite_code: string | null
          creator_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          type: string
          start_date?: string | null
          end_date?: string | null
          location?: string | null
          invite_code?: string | null
          creator_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          type?: string
          start_date?: string | null
          end_date?: string | null
          location?: string | null
          invite_code?: string | null
          creator_id?: string
          updated_at?: string
        }
      }
      timezone_members: {
        Row: {
          id: string
          timezone_id: string
          user_id: string
          role: string
          joined_at: string
        }
        Insert: {
          id?: string
          timezone_id: string
          user_id: string
          role?: string
          joined_at?: string
        }
        Update: {
          id?: string
          timezone_id?: string
          user_id?: string
          role?: string
          joined_at?: string
        }
      }
      media: {
        Row: {
          id: string
          memory_id: string
          type: string
          storage_url: string
          thumbnail_url: string | null
          file_name: string
          file_size: number
          mime_type: string
          created_at: string
        }
        Insert: {
          id?: string
          memory_id: string
          type: string
          storage_url: string
          thumbnail_url?: string | null
          file_name: string
          file_size: number
          mime_type: string
          created_at?: string
        }
        Update: {
          id?: string
          memory_id?: string
          type?: string
          storage_url?: string
          thumbnail_url?: string | null
          file_name?: string
          file_size?: number
          mime_type?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
} 