-- Add missing fields to github_connections table
ALTER TABLE github_connections 
ADD COLUMN IF NOT EXISTS token_type TEXT DEFAULT 'bearer',
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS last_error TEXT,
ADD COLUMN IF NOT EXISTS last_validated TIMESTAMP WITH TIME ZONE;

-- Update github_repositories table to add missing fields
ALTER TABLE github_repositories
ADD COLUMN IF NOT EXISTS clone_url TEXT,
ADD COLUMN IF NOT EXISTS language TEXT,
ADD COLUMN IF NOT EXISTS size INTEGER,
ADD COLUMN IF NOT EXISTS stargazers_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS forks_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_issues BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS has_projects BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS has_wiki BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS permissions JSONB,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;